In [1]:
import pandas as pd                  #Importing necessary documents
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv('D:\Summer 2022\Datascience Projects UDEMY\Project2/data.csv',error_bad_lines=False) #Read data using pandas

b'Skipping line 2810: expected 2 fields, saw 5\nSkipping line 4641: expected 2 fields, saw 5\nSkipping line 7171: expected 2 fields, saw 5\nSkipping line 11220: expected 2 fields, saw 5\nSkipping line 13809: expected 2 fields, saw 5\nSkipping line 14132: expected 2 fields, saw 5\nSkipping line 14293: expected 2 fields, saw 5\nSkipping line 14865: expected 2 fields, saw 5\nSkipping line 17419: expected 2 fields, saw 5\nSkipping line 22801: expected 2 fields, saw 5\nSkipping line 25001: expected 2 fields, saw 5\nSkipping line 26603: expected 2 fields, saw 5\nSkipping line 26742: expected 2 fields, saw 5\nSkipping line 29702: expected 2 fields, saw 5\nSkipping line 32767: expected 2 fields, saw 5\nSkipping line 32878: expected 2 fields, saw 5\nSkipping line 35643: expected 2 fields, saw 5\nSkipping line 36550: expected 2 fields, saw 5\nSkipping line 38732: expected 2 fields, saw 5\nSkipping line 40567: expected 2 fields, saw 5\nSkipping line 40576: expected 2 fields, saw 5\nSkipping line 

In [3]:
data.dropna(inplace=True)  #dropping the rows containing no password.
data.isnull().sum()        #checking if there is no such row existing

password    0
strength    0
dtype: int64

In [4]:
data.head()

password  strength
0     kzde5577         1
1     kino3434         1
2    visi7k1yr         1
3     megzy123         1
4  lamborghin1         1

In [5]:
password_tuple=np.array(data)    #storing the whole data as array
password_tuple

array([['kzde5577', 1],
       ['kino3434', 1],
       ['visi7k1yr', 1],
       ...,
       ['184520socram', 1],
       ['marken22a', 1],
       ['fxx4pw4g', 1]], dtype=object)

In [6]:
import random                     
random.shuffle(password_tuple)     #shuffling data in order to create more representative training set

x=[labels[0] for labels in password_tuple]  #storing passwords in x
y=[labels[1] for labels in password_tuple]  #storing strenghts in y ,

In [7]:
def word_divide_char(inputs): #function returning the string, characterwise
    character=[]
    for i in inputs:
        character.append(i)
    return character

In [8]:
!pip install -U scikit-learn  #installed scikit learn for performing ML Algorithms


[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip


ERROR: Invalid requirement: '#installed'


In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer #Performing TF-IDF on the data


In [10]:
vectorizer=TfidfVectorizer(tokenizer=word_divide_char)
X=vectorizer.fit_transform(x) #Feature extraction of the passwords
X.shape

(669639, 127)

In [11]:
first_document_vector=X[0]  # Checking the TF*IDF matrix of first word
first_document_vector.T.todense()

matrix([[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.56707125],
        [0.        ],
        [0.59113914],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0

In [12]:
df=pd.DataFrame(first_document_vector.T.todense(),index=vectorizer.get_feature_names(),columns=['TF-IDF'])
df.sort_values(by=['TF-IDF'],ascending=False)

TF-IDF
7   0.591139
5   0.567071
z   0.336536
k   0.291942
d   0.285757
..       ...
?   0.000000
>   0.000000
=   0.000000
<   0.000000
™   0.000000

[127 rows x 1 columns]

In [13]:
from sklearn.model_selection import train_test_split  #scikit learn for performing train test runs
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2) # By taking 80% of training data and remaining test data

In [14]:
from sklearn.linear_model import LogisticRegression  #Logistic regression performed since it is a classfication problem
clf=LogisticRegression(random_state=0,multi_class='multinomial') #multinomial since we have two classify in 3 ranges for password, i.e. 0,1,2

In [15]:
clf.fit(X_train,y_train)

LogisticRegression(multi_class='multinomial', random_state=0)

In [16]:
dt=np.array(['7@4r9gslh897treusbcfk']) #Now based on the training set, let us check for this password
pred=vectorizer.transform(dt)
clf.predict(pred) #The output I expect is to be 2, since it is very stong

array([2])

In [17]:
dt=np.array(['7r79gtor'])  #TEST CASE 2 for moderate password
pred=vectorizer.transform(dt)
clf.predict(pred)

array([1])

In [18]:
dt=np.array(['123456'])  #TEST CASE 3 for a moderate password
pred=vectorizer.transform(dt)
clf.predict(pred)

array([1])

In [19]:
dt=np.array(['abcd'])   #TEST CASE 4 for a weak password
pred=vectorizer.transform(dt)
clf.predict(pred)

array([0])

In [20]:
y_pred=clf.predict(X_test)  #Now we predict values for the test data
y_pred

array([1, 1, 1, ..., 1, 0, 1])

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)  
print(cm)                               #Output gives the confusion matrix for our test data based on our prediction
print(accuracy_score(y_test,y_pred))    #Ouput of accuracy of prediction of test data. Not that bad.

[[ 5511 12426    14]
 [ 3911 92884  2488]
 [   32  5174 11488]]
0.8204632339764649


In [22]:
from sklearn.metrics import classification_report 
print(classification_report(y_test,y_pred))  #Classification report for our prediction of test data

              precision    recall  f1-score   support

           0       0.58      0.31      0.40     17951
           1       0.84      0.94      0.89     99283
           2       0.82      0.69      0.75     16694

    accuracy                           0.82    133928
   macro avg       0.75      0.64      0.68    133928
weighted avg       0.80      0.82      0.80    133928

